<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pbr_stage</name>
  <version>1.0.0</version>
  <description>Stage worlds, objects and maps of the pbr environments.</description>

  <maintainer email="benjamin.kisliuk@dfki.de">Benjamin Kisliuk</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
