<?xml version="1.0"?>
<package format="3">
  <name>pbr_gazebo</name>
  <version>0.0.1</version>
  <description>This package contains files for pbr simulation with gazebo.</description>

  <maintainer email="oscar.lima@dfki.de">Oscar Lima</maintainer>
  <author email="sebastian.stock@dfki.de">Sebastian Stock</author>
  <author email="nils.niemann@dfki.de">Nils Niemann</author>

  <license>BSD-3-Clause</license>

  <url type="repository">https://github.com/DFKI-NI/pbr_tools</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_python</depend>
  <depend>launch_ros</depend>
  <depend>ros_gz_sim</depend>

  <export>
    <build_type>ament_cmake</build_type>
    <!-- documentation available at: https://github.com/gazebosim/ros_gz/blob/jazzy/ros_gz_sim/README.md -->
    <gazebo_ros gazebo_model_path="${prefix}/../"/>
    <gazebo_ros gazebo_media_path="${prefix}/worlds/"/>
  </export>

</package>
